# Generated by Django 4.2.4 on 2023-08-27 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'maker',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'OS',
                'db_table': 'os',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'ram',
                'db_table': 'ram',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('info', models.TextField(blank=True)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1000000000.0), django.core.validators.MinValueValidator(0)])),
                ('screen_diagonal', models.FloatField()),
                ('battery_capacity', models.IntegerField()),
                ('resolution_main_camera', models.FloatField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.color')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.maker')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.os')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.ram')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
